### ISSUE TITLE
First Task Progress Update

### ISSUE THREAD

**Issue by Gregorvich** [Gregorvich/dungeon-omega#2]
As you know I had a busy last few weeks, but I guess that's no excuse for not posting updates on this project. At any rate, I will try to be more consistent with my updates on the tasks at hand moving forward.

Here's the game plan moving forward in terms of what the closed issue talked about:
- I will build the Hello World program using at least two functions (probably a main function that calls the "Hello World" function, but I guess all projects need a function called "main" in order for the compiler to work without complaint. Lol)
- As I do the previous task I will figure out how to upload the files to Github using the Git application. I am a bit rusty on using Version Control but learning that will be the fun part
- I will NOT work on the master branch/ merge directly into the master branch because that would be silly. I will create my own branch which will be reviewed by the team before merging or something like that.
- Since this is a pretty basic task I don't think I will have many questions, but if I come across something related to proper Github usage or something Python related, I will ask Senpai.

There you have it. In terms of the completion date for this task, I will try to have it done by Thursday night, or Friday at the latest.

Cheers,
Adam Gregor

**Comment by Jacob-Gregor** [comment]
1. Do not create separate issues for updates. Try to contain similar or related tasks in a single issue. I posted your update in the original issue and re-opened it.

2. Going forward do not post personal messages in the issues nor in the comments. Try to keep all updates and communication here on a "professional" level. This will be good practice for any future work you do with others either on GitHub or any other medium.

I will close this issue since I opened the original one.

Also in accordance to my 2nd bullet point, I removed your personal message to me from the description since this is not the medium for such conversation and because this is a public repository that anyone can look at.
