### ISSUE TITLE
Flask Tutorial

### ISSUE THREAD

**Issue by Jacob-Gregor** [Gregorvich/dungeon-omega#5]
One of the new modules we will be using is something called Flask. Now, I don't want to go over something in a half-baked way. So here is a tutorial that seems to go over Flask quite well.

https://programminghistorian.org/en/lessons/creating-apis-with-python-and-flask

Now, you can choose to follow this tutorial on your own and see how far you get or just study it. 

What you shouldn't do is try and put Flask in your code yet. This is just because, as your code is today, it wouldn't work without some refactoring and reimagining of  the overall flow.  Instead, before we put flask in, we will need to first define the use-cases we will have and create functions or API pipelines based on that.

Go ahead and update this issue with your progress and questions about anything I said here or the tutorial. We will call this issue done once you either mess around with the tutorial enough or if you've studied it enough and we have a discussion on next steps for the code.

**Comment by Gregorvich** [comment]
I went through the tutorial and studied it carefully, and after doing so I feel as though I have an adequate understanding of API's and the flask extension for Python for continuing this project. I don't really have much experience with databases or SQLite, but after looking through the resource you posted it kind of makes sense to me, such as how queries are used to look through a database object, and how we also provide a list of filter values in tandem with the query we provide.

One question I do have is that I am not exactly sure why both of these are needed for the execute method that is used with the cursor object. So why would we need both of these things in order to find data in the database? What is the role of each of these two things when it comes to acquiring database information?

Also, the tutorial mentions that the syntax for SQL queries is the following:
'SELECT <columns> FROM <table> WHERE <column=match> AND <column=match>;'
However, I'm not sure if the first column is supposed to actually be <rows>, because each row is a book entry, while the columns are each book's properties. So, wouldn't we want to select the books we want from the database, and not columns of specific data? There were some typos in the tutorial I noticed, so I wasn't sure if this was one of them or if queries are actually supposed to select columns when reaching into the database.

Those are pretty nitpicky things that I had questions about. Overall I feel as though I have a pretty good understanding of what API's are, and what elements make an API a "good" and "user-friendly" API.

**Comment by Gregorvich** [comment]
The syntax I posted for SQL queries got funky for some reason, but if you look at the tutorial in the section "Understanding Our Database-Powered API", you can see the syntax I was referencing.

**Comment by Jacob-Gregor** [comment]
Let's not focus on the sql lite portion for now. We are a few steps away from doing anything with it. And we may not even use it depending on  what we want to accomplish. 

If you got a good understanding Flask, then we can call this issue done.
