### ISSUE TITLE
Integrate Flask within code base

### ISSUE THREAD

**Issue by Viedan** [Gregorvich/dungeon-omega#7]
1. Get the code base is a great spot to accomplish tasks needed for an API. Right now I would say it is in a pre-POC stage. (POC means Proof of Concept)
2. Integrate the Flask module into the code base. This will allow us to make HTTP calls and more

The goal is to integrate flask and get it working locally.

This is POC work, so start simple.

**Comment by Gregorvich** [comment]
Hey Jacob, just a quick update. I've been reviewing some flask concepts since it's been a couple weeks since I last reviewed the flask tutorial you posted earlier, and I am now in the process of implementing flask into our project. I should have something for you to look at by the end of tomorrow. As always, I will let you know if I have any questions.

**Comment by Jacob-Gregor** [comment]
Sounds good. If you want to demo anything to me as well, just let me know.

**Comment by Gregorvich** [comment]
Hey Jacob, the project is going well, I should have something for you to look at by sometime tomorrow, probably before 6:00 p.m. I know it's been awhile since I last updated, but some stuff came up which hindered my progress on the project momentarily. Sorry for the late update at any rate. The plan is to get the codebase and a large amount of the project completed overall this weekend, that way this week should be just tidying things up and implementing whatever additional features we find necessary. So, I should be able to have the project completely finished by this Friday, December 25th. I hope things are going well on your end, and I will talk to you soon

**Comment by Gregorvich** [comment]
Hey Jacob.

I pushed a new branch to Github called APIPrototypeV1 that has the code so far for the API that we are creating. I accidently kept working on my local serverfix branch after you pulled my remote serverfix branch into the master branch on our server, which meant that my local serverfix branch wasn't tracking anything since origin/serverfix was no longer there. No need to worry about it, however, because I just created a new remote branch called APIPrototypeV1 and set my serverfix branch to track the origin/APIPrototypeV1 branch, so that I will be able to push my commits like normal and you shouldn't be able to tell the difference or anything. I was also sure to update my local master branch, since I had also forgotten to update it after the remote serverfix branch was merged into the remote master branch. If the need arises for me to create an additional branch after the APIPrototypeV1 branch is merged into master or for any other reason, I will be sure to base it off my local master first to avoid any issues. Just thought I would let you know.

As for the actual branch itself, the main thing that I added is an SQLite database, which can be used to test our API's functionality more conveniently than hardcoding a database into a local Python file. Or at least I thought so anyway. I also started working on the actual API, which is located in the Sorcery_API.py file. It is a work in progress right now, so don't pay it too much mind; I plan on continuing to work on it pretty soon here. I will continue working on creating the API and will upload it to Github once it is functionable to a certain degree. Or if I just feel like sharing how the work is going or something.

Let me know if you have any questions about the code. As I mentioned earlier, the main thing you can check out is the code for initializing the database, since that is basically finished. It is located in the Sorcery_Database.py file.

**Comment by Gregorvich** [comment]
Hey Jacob, I just pushed an update to the APIPrototypeV1 branch that adds some functionality to our API. It seems to work for the most part, so let me know what you think of it. Here is an overview of what you can do and how you should run the code:

1. You can run the code for the API by simply executing the Sorcery_API.py file from the command line. From there you should have access to a local server where you can test out the functions defined in Sorcery_API.py by sending different URL requests to the server.
2. The path that you can provide to the domain to receive everything from the database is /api/v1/resources/sorceries/all
3. You can input parameters to filter the search results, such using the "elemental_alignment" parameter to filter sorceries by their element. You can look at the specific syntax for doing so by looking at the source code

Let me know if this is satisfactory for our codebase, or if you have any specific requests. Also let me know if you have any questions about the code or using the API.

**Comment by Jacob-Gregor** [comment]
Thanks. I'll take a look tomorrow

**Comment by Gregorvich** [comment]
Hey Jacob. I just pushed a new update to the APIPrototypeV1 branch. The main part of the update is that I re-organized much of the existing code, as well as adding functionality for a Spellbook class. Here are the highlights:

1. A new class called Spellbook was added, since it made more sense to have an actual Spellbook object rather than just a list of spells. Along with this, there are now class methods for manipulating Spellbooks, such as adding Sorceries, retrieving Sorcery objects, etc. Additionally, the printSpellBook() function is now a method of the Spellbook class, and has thus has been removed from the Sorcery_Functions.py module and is now located in the Spellbooks.py module
2. The createSpells function was moved to a new file called Sorcery_Helper_Functions.py
3. An additional function was added to the Main.py file to assist with testing the new Spellbook class
4. Some bug fixes were made in the Sorcery_API file to ensure that searching for Sorceries in the database using parameters functioned correctly. More specifically, the forbiddenStatus variable should not have been converted to a boolean, since, in the instance where forbidden_status was not one of the parameters provided in the URL request, the value returned from queryParameters.get("forbidden_status") was set to be -1. Therefore, converting this value to a boolean would change it to the value True, which was unintentional. This caused unexpected results when performing a URL request to the database with filters, and when the forbidden_status parameter was not being used

So there you have it. I was going to make additional changes to the actual API, like how were talked about, but I'm a bit unclear about what you wanted me to change about it. We talked about moving most of the code of the functions in Sorceries_API.py to functions in the Sorcey_Functions.py file, but that doesn't make much sense to me from an OOP standpoint because I don't know if it makes sense for Sorcery objects to have methods relating to API. Also, if I moved the bulk of the source code in Sorcery_API.py to methods in the Sorcery class, then that would mean I would have to create a Sorcery object and use Sorcery methods with that object to perform API functions, which sounds strange. I thought about making Sorcery_API it's own class, but I'm not entirely sure what the benefit of this would be or if it would make much sense to do this.

What changes would you recommend I make to the Sorceries_API.py file, and what exactly would the objective of these changes be? I know it's important to modulate different parts of the source files so that you do not have global variables just hanging around that users might not actually want, so I'm guessing the changes I make to Sorceries_API to make it more organized would have something to do with that.

Also, let me know if you have trouble running the program. I think you should be able to run it as long as you have a Windows 10 operating system and are using Python 3 or later.

**Comment by Jacob-Gregor** [comment]
Go ahead and open a pull request against the master branch and I'll review everything from there.

**Comment by Jacob-Gregor** [comment]
Calling this "done"

Flask is implemented, however the code base is a bit unorganized. Both from a execution standpoint (running the application), and from a code standpoint (proper set/get functions, removing test functions, etc)
